### ISSUE TITLE
Object's properties extraction

### ISSUE THREAD

**Issue by vodkar** [bimspot/xeokit-metadata#11] opened 2020-09-21 07:54 UTC
Hi!

I want to add feature to extract properties of objects. I think it's good idea to execute converter with arg `--props <prop1>,<prop2>,...`. What you think about this?

Is there any contribute rules?

**Comment by eriadam** [comment] 2020-09-21 12:47
Hey @vodkar , thanks for the contribution. I just pushed the guide we use: https://github.com/bimspot/xeokit-metadata/blob/develop/CONTRIBUTING.md

Would you maybe summarise the feature you would like to add, please?

**Comment by vodkar** [comment] 2020-09-21 17:42
Okey, thanks, @eriadam!

We had added new property to element and export to .ifc file. 

Example from our .ifc file:
`#974= IFCPROPERTYSINGLEVALUE('ms_ID',$,IFCTEXT('90894'),$);`

Then, we need to use property `ms_ID` in model, there's special attribute for properties: https://xeokit.github.io/xeokit-sdk/docs/class/src/viewer/metadata/MetaObject.js~MetaObject.html#instance-member-properties 

Now, this properties not used, when converting from ifc to json.

**Comment by eriadam** [comment] 2020-09-22 20:04
Thanks, understood. Makes sense.

@xeolabs would you have any recommendation on using this property?

**Comment by eriadam** [comment] 2021-01-05 12:38
Closing as duplicate of https://github.com/bimspot/xeokit-metadata/issues/12.

**Closed by eriadam** 2021-01-05 12:38 UTC
Labels: enhancement
